folders:
  root_dir: ../
  subdirectories:
  - ../models
  - ../slides
  - ../transformers
  - ../.ipynb_checkpoints
  - ../.git
  - ../data
  - ../notebooks
  - ../.git/objects
  - ../.git/info
  - ../.git/logs
  - ../.git/hooks
  - ../.git/refs
  - ../.git/objects/95
  - ../.git/objects/92
  - ../.git/objects/66
  - ../.git/objects/50
  - ../.git/objects/03
  - ../.git/objects/32
  - ../.git/objects/35
  - ../.git/objects/3c
  - ../.git/objects/3d
  - ../.git/objects/67
  - ../.git/objects/93
  - ../.git/objects/0e
  - ../.git/objects/05
  - ../.git/objects/9c
  - ../.git/objects/02
  - ../.git/objects/a4
  - ../.git/objects/a3
  - ../.git/objects/ad
  - ../.git/objects/bb
  - ../.git/objects/d7
  - ../.git/objects/d0
  - ../.git/objects/b3
  - ../.git/objects/b4
  - ../.git/objects/a5
  - ../.git/objects/d1
  - ../.git/objects/ae
  - ../.git/objects/d8
  - ../.git/objects/ab
  - ../.git/objects/f4
  - ../.git/objects/f3
  - ../.git/objects/c9
  - ../.git/objects/fd
  - ../.git/objects/f2
  - ../.git/objects/f5
  - ../.git/objects/cf
  - ../.git/objects/ca
  - ../.git/objects/c8
  - ../.git/objects/fb
  - ../.git/objects/c6
  - ../.git/objects/ec
  - ../.git/objects/18
  - ../.git/objects/pack
  - ../.git/objects/11
  - ../.git/objects/29
  - ../.git/objects/42
  - ../.git/objects/1f
  - ../.git/objects/74
  - ../.git/objects/8f
  - ../.git/objects/8a
  - ../.git/objects/19
  - ../.git/objects/75
  - ../.git/objects/86
  - ../.git/objects/72
  - ../.git/objects/44
  - ../.git/objects/38
  - ../.git/objects/6e
  - ../.git/objects/31
  - ../.git/objects/info
  - ../.git/objects/65
  - ../.git/objects/62
  - ../.git/objects/98
  - ../.git/objects/30
  - ../.git/objects/5b
  - ../.git/objects/37
  - ../.git/objects/01
  - ../.git/objects/6c
  - ../.git/objects/39
  - ../.git/objects/99
  - ../.git/objects/52
  - ../.git/objects/55
  - ../.git/objects/0f
  - ../.git/objects/0a
  - ../.git/objects/90
  - ../.git/objects/bf
  - ../.git/objects/d3
  - ../.git/objects/d4
  - ../.git/objects/ba
  - ../.git/objects/b8
  - ../.git/objects/b1
  - ../.git/objects/d5
  - ../.git/objects/af
  - ../.git/objects/b7
  - ../.git/objects/db
  - ../.git/objects/a8
  - ../.git/objects/a1
  - ../.git/objects/e1
  - ../.git/objects/cd
  - ../.git/objects/cc
  - ../.git/objects/e6
  - ../.git/objects/f0
  - ../.git/objects/fa
  - ../.git/objects/ff
  - ../.git/objects/c5
  - ../.git/objects/f6
  - ../.git/objects/e9
  - ../.git/objects/f1
  - ../.git/objects/e7
  - ../.git/objects/ce
  - ../.git/objects/46
  - ../.git/objects/79
  - ../.git/objects/2d
  - ../.git/objects/77
  - ../.git/objects/70
  - ../.git/objects/1e
  - ../.git/objects/24
  - ../.git/objects/4f
  - ../.git/objects/8d
  - ../.git/objects/15
  - ../.git/objects/1d
  - ../.git/objects/1c
  - ../.git/objects/49
  - ../.git/objects/2e
  - ../.git/objects/78
  - ../.git/objects/13
  - ../.git/objects/14
  - ../.git/objects/22
  - ../.git/objects/25
  - ../.git/logs/refs
  - ../.git/logs/refs/heads
  - ../.git/logs/refs/remotes
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/refs/heads
  - ../.git/refs/tags
  - ../.git/refs/remotes
  - ../.git/refs/remotes/origin
  - ../.git/logs/refs/heads
  - ../.git/logs/refs/remotes
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../data/.ipynb_checkpoints
  - ../notebooks/__pycache__
  - ../notebooks/yaml utilities
  - ../notebooks/.ipynb_checkpoints
  - ../notebooks/yaml utilities/.ipynb_checkpoints
  - ../.git/objects/95
  - ../.git/objects/92
  - ../.git/objects/66
  - ../.git/objects/50
  - ../.git/objects/03
  - ../.git/objects/32
  - ../.git/objects/35
  - ../.git/objects/3c
  - ../.git/objects/3d
  - ../.git/objects/67
  - ../.git/objects/93
  - ../.git/objects/0e
  - ../.git/objects/05
  - ../.git/objects/9c
  - ../.git/objects/02
  - ../.git/objects/a4
  - ../.git/objects/a3
  - ../.git/objects/ad
  - ../.git/objects/bb
  - ../.git/objects/d7
  - ../.git/objects/d0
  - ../.git/objects/b3
  - ../.git/objects/b4
  - ../.git/objects/a5
  - ../.git/objects/d1
  - ../.git/objects/ae
  - ../.git/objects/d8
  - ../.git/objects/ab
  - ../.git/objects/f4
  - ../.git/objects/f3
  - ../.git/objects/c9
  - ../.git/objects/fd
  - ../.git/objects/f2
  - ../.git/objects/f5
  - ../.git/objects/cf
  - ../.git/objects/ca
  - ../.git/objects/c8
  - ../.git/objects/fb
  - ../.git/objects/c6
  - ../.git/objects/ec
  - ../.git/objects/18
  - ../.git/objects/pack
  - ../.git/objects/11
  - ../.git/objects/29
  - ../.git/objects/42
  - ../.git/objects/1f
  - ../.git/objects/74
  - ../.git/objects/8f
  - ../.git/objects/8a
  - ../.git/objects/19
  - ../.git/objects/75
  - ../.git/objects/86
  - ../.git/objects/72
  - ../.git/objects/44
  - ../.git/objects/38
  - ../.git/objects/6e
  - ../.git/objects/31
  - ../.git/objects/info
  - ../.git/objects/65
  - ../.git/objects/62
  - ../.git/objects/98
  - ../.git/objects/30
  - ../.git/objects/5b
  - ../.git/objects/37
  - ../.git/objects/01
  - ../.git/objects/6c
  - ../.git/objects/39
  - ../.git/objects/99
  - ../.git/objects/52
  - ../.git/objects/55
  - ../.git/objects/0f
  - ../.git/objects/0a
  - ../.git/objects/90
  - ../.git/objects/bf
  - ../.git/objects/d3
  - ../.git/objects/d4
  - ../.git/objects/ba
  - ../.git/objects/b8
  - ../.git/objects/b1
  - ../.git/objects/d5
  - ../.git/objects/af
  - ../.git/objects/b7
  - ../.git/objects/db
  - ../.git/objects/a8
  - ../.git/objects/a1
  - ../.git/objects/e1
  - ../.git/objects/cd
  - ../.git/objects/cc
  - ../.git/objects/e6
  - ../.git/objects/f0
  - ../.git/objects/fa
  - ../.git/objects/ff
  - ../.git/objects/c5
  - ../.git/objects/f6
  - ../.git/objects/e9
  - ../.git/objects/f1
  - ../.git/objects/e7
  - ../.git/objects/ce
  - ../.git/objects/46
  - ../.git/objects/79
  - ../.git/objects/2d
  - ../.git/objects/77
  - ../.git/objects/70
  - ../.git/objects/1e
  - ../.git/objects/24
  - ../.git/objects/4f
  - ../.git/objects/8d
  - ../.git/objects/15
  - ../.git/objects/1d
  - ../.git/objects/1c
  - ../.git/objects/49
  - ../.git/objects/2e
  - ../.git/objects/78
  - ../.git/objects/13
  - ../.git/objects/14
  - ../.git/objects/22
  - ../.git/objects/25
  - ../.git/logs/refs
  - ../.git/logs/refs/heads
  - ../.git/logs/refs/remotes
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/refs/heads
  - ../.git/refs/tags
  - ../.git/refs/remotes
  - ../.git/refs/remotes/origin
  - ../.git/logs/refs/heads
  - ../.git/logs/refs/remotes
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../notebooks/yaml utilities/.ipynb_checkpoints
  - ../.git/logs/refs/heads
  - ../.git/logs/refs/remotes
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
  - ../.git/logs/refs/remotes/origin
