folders:
  root_dir: ../
  subdirectories:
  - ../models
       - ARIMA_1_1_0_t0_forecaster.pkl
        params = p=1, d=1, 1=0

        - knn_win_length_10_n_5.pkl
        eindow length = 10; nearest neighbors = 5

        - prophet_forecaster.pkl

        - SES_forecaster.pkl  
          smoothing level = 0.5 sp=365. trend = none

  - ../slides

  - ../transformers
          - differencer.pkl

  - ../data
           cleaned_^DJl.csv

           cleaned_^GSPC.csv

           cleaned_^IXIC.csv

           cleaned_^NDX.csv

           cleaned_AAPL.csv

           cleaned_GOOGL.csv

           cleaned_IBM.csv

           cleaned_META.csv

           cleaned_MSFT.csv

           cleaned_NVDA.csv

           raw_^DJI.csv

           raw_^GSPC.csv

           raw_^IXIC.csv

           raw_^NDX.csv

           raw_aapl.csv

           raw_googl.csv

           raw_ibm.csv

           raw_META.csv

           raw_msft.csv

           raw_NDX.csv

           raw_NVDA.csv
  - ../notebooks
            - project_main.ipynb
            - functions.py
